module.exports = {
    staging: {
      baseUrl: "https://live-web-sheridan.pantheonsite.io",
      urls: [
        "/",
        "/about/",
        "/academic-calendar/",
        "/admissions/",
        "/apply/",
        "/apply/?d={internal_program_code}",
        "/apply/?d=SHERIDAN.CA-B-BCPTRSCI",
        "/apply/?d=SHERIDAN.CA-B-BINFOSCICBRSEC",
        "/apply/?d=SHERIDAN.CA-B-BSCLCMTYDEV",
        "/apply/?d=SHERIDAN.CA-B-GENARTSSCIIS",
        "/apply/?d=URI-B-RNBS",
        "/apply/?d=URI-B-RNBS&calculator=true",
        "/degrees/area/",
        "/degrees/area/prototype/",
        "/privacy-policy/",
        "/degrees/undergraduate/",
        "/degrees/undergraduate/bachelors-computer-information-science/",
        "/degrees/",
        "/degrees/undergraduate/bachelors-computer-information-science/cyber-security/",
        "/degrees/undergraduate/bachelors-computer-information-science/general/",
        "/degrees/undergraduate/bachelors-social-community-development/",
        "/degrees/undergraduate/general-arts-science-university-profile/",
        "/online-experience/",
        "/request-info/",
        "/apply?d=URI-B-RNBS&calculator=true",
        "/student-services/",
        "/tuition/"
      ]
    },
    prod: {
      baseUrl: "https://online.sheridancollege.ca",
      urls: [
        "https://online.sheridancollege.ca/",
        "https://online.sheridancollege.ca/about/",
        "https://online.sheridancollege.ca/academic-calendar/",
        "https://online.sheridancollege.ca/admissions/",
        "https://online.sheridancollege.ca/apply/",
        "https://online.sheridancollege.ca/apply/?d={internal_program_code}",
        "https://online.sheridancollege.ca/apply/?d=SHERIDAN.CA-B-BCPTRSCI",
        "https://online.sheridancollege.ca/apply/?d=SHERIDAN.CA-B-BINFOSCICBRSEC",
        "https://online.sheridancollege.ca/apply/?d=SHERIDAN.CA-B-BSCLCMTYDEV",
        "https://online.sheridancollege.ca/apply/?d=SHERIDAN.CA-B-GENARTSSCIIS",
        "https://online.sheridancollege.ca/apply/?d=URI-B-RNBS",
        "https://online.sheridancollege.ca/apply/?d=URI-B-RNBS&calculator=true",
        "https://online.sheridancollege.ca/degrees/area/",
        "https://online.sheridancollege.ca/degrees/area/prototype/",
        "https://online.sheridancollege.ca/privacy-policy/",
        "https://online.sheridancollege.ca/degrees/undergraduate/",
        "https://online.sheridancollege.ca/degrees/undergraduate/bachelors-computer-information-science/",
        "https://online.sheridancollege.ca/degrees/",
        "https://online.sheridancollege.ca/degrees/undergraduate/bachelors-computer-information-science/cyber-security/",
        "https://online.sheridancollege.ca/degrees/undergraduate/bachelors-computer-information-science/general/",
        "https://online.sheridancollege.ca/degrees/undergraduate/bachelors-social-community-development/",
        "https://online.sheridancollege.ca/degrees/undergraduate/general-arts-science-university-profile/",
        "https://online.sheridancollege.ca/online-experience/",
        "https://online.sheridancollege.ca/request-info/",
        "https://online.sheridancollege.ca/apply?d=URI-B-RNBS&calculator=true",
        "https://online.sheridancollege.ca/student-services/",
        "https://online.sheridancollege.ca/tuition/"
      ]
    }
  };